#!/bin/sh
# Xcode Cloud runs this right after cloning, before it resolves the project.
#
# It has to exist because `ios/` is generated by `expo prebuild` and is not in
# git — a fresh clone has an app with no Xcode project at all. This rebuilds it
# from app.json and the config plugins, which is the same thing a developer's
# machine does, so CI and local builds cannot drift.
#
# It lives inside `ios/` rather than at the repository root because Xcode Cloud
# looks for `ci_scripts` beside the workspace named in the workflow, and nowhere
# else. That is why `.gitignore` carves this one directory out of the ignored
# `ios/` tree.
set -eu

cd "$CI_PRIMARY_REPOSITORY_PATH/mobile"

# The build images ship no Node. Match the version the repo asks for rather
# than whatever brew calls current, so CI compiles the same tree as a laptop.
if ! command -v node >/dev/null 2>&1; then
    brew install node@24
    brew link node@24 --force --overwrite
fi
corepack enable

# --frozen-lockfile so a build can never quietly resolve a different dependency
# tree than the one that was reviewed. `mobile/` is its own pnpm workspace with
# its own lockfile, so this installs that graph and not the desktop app's.
pnpm install --frozen-lockfile

# No --clean: it would delete the directory this script is running from, and a
# fresh clone has nothing stale to clear anyway.
#
# APS_ENVIRONMENT comes from the workflow's environment variables and is read by
# the aps-environment config plugin. Unset means development, which would make
# a TestFlight build register for sandbox pushes and render every notification
# as placeholder text.
npx expo prebuild --platform ios

cd ios
pod install
